liquibase:
    context: dev

spring:
    profiles:
        active: dev
    datasource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url: jdbc:postgresql://localhost:5432/postgres
        databaseName:
        serverName:
        username: postgres
        password: password
