liquibase:
    context: dev

spring:
    profiles:
        active: dev
    datasource:
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1
        databaseName:
        serverName:
        username:
        password:
